### ISSUE TITLE
[Bug] Note title doesn't hava a place holder

### ISSUE THREAD

**Issue by Nux404** [t4zzlerdeveloper/rubium#13]
**Describe the bug**
[Portuguese]
Quando crias uma nova nota e apagas o título, **não** tens uma descrição / instrução de onde devas começar a escrever.

**To Reproduce**
1. Create a new note
2. Delete the note name
3. See error

**Expected behavior**
[Portuguese]
Quando crias uma nota nova e apagas o título dela, devias ter uma descrição como tens quando queres adicionar um bloco novo (ex.: Título H1 que aparece "Introduz um Título H1..." ).

**Screenshots**
![image~Rubium](https://github.com/t4zzlerdeveloper/rubium/assets/127152848/8b29a594-a705-44a5-8916-b63408ed50f8)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 124.0.6367.92

**Comment by t4zzlerdeveloper** [comment]
Thank you for reporting this UI bug, fixed in [50ebafc](https://github.com/t4zzlerdeveloper/rubium/commit/50ebafcbdcedb4351b03abceafb9c8849fa1bc48)
