### ISSUE TITLE
Parágrafos tamanho

### ISSUE THREAD

**Issue by Gil124** [t4zzlerdeveloper/rubium#3]
**Describe the bug**
Se escrever num parágrafo e ele ficar maior que uma linha e eu apagar não volta a ter uma linha

**To Reproduce**
1. Criar um parágrafo
2. Dar enter ou escrever mais do que uma linha
3. Apagar uma das linhas ou várias
4. Observar que o tamanho do div não diminuiu

**Expected behavior**
Seria esperado o tamanho reduzir e aumentar de acordo com o texto presente nele

**Screenshots**
![image](https://github.com/t4zzlerdeveloper/rubium/assets/47061119/d6dda4b3-49a2-46a1-a28a-cf0ece8ad4df)
![image](https://github.com/t4zzlerdeveloper/rubium/assets/47061119/9441e532-7ec2-4a15-b215-9ccffcce04f4)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Vivaldi
 - Version 11
  
 - **Smartphone (please complete the following information):**

**Additional context**

**Comment by t4zzlerdeveloper** [comment]
Bug fixed in commit e53ff28, it will be live on the production website in the next deploy
