### ISSUE TITLE
Descreasing screen width

### ISSUE THREAD

**Issue by Gil124** [t4zzlerdeveloper/rubium#4]
**Describe the bug**
When I decrease the screen width and there's elements within my note t some of them become less visible

**To Reproduce**
1. Create various new elements an write on them at least 2 lines
2.  Decrease your screen width
4. Observe that some of the parts are not visible

**Expected behavior**
it would be expected that the content view would fit the screen size

**Screenshots**
![image](https://github.com/t4zzlerdeveloper/rubium/assets/47061119/b6b080d0-8486-4415-b012-09c9572281a3)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Vivaldi
 - Version present

**Smartphone (please complete the following information):**

**Additional context**

**Comment by t4zzlerdeveloper** [comment]
Solved in commit 363c45a, closing this issue.
Soon in the production version!
